/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacepok;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pokemons.Ginasio;
import pokemons.Informacoes;
import pokemons.Pokedex;

/**
 *
 * @author Juarez
 */
public class TelaConsultaGinasio extends javax.swing.JInternalFrame {

    /**
     * Retorna o Objeto Pokedex Salvo
     * @return 
     */
    public Pokedex getObjecto(){
        
        try{
            
            //Carrega o arquivo
 
            FileInputStream arquivoLeitura = new FileInputStream("gravObj.dat");
            ObjectInputStream objLeitura = new ObjectInputStream(arquivoLeitura);
            Pokedex pok = (Pokedex)objLeitura.readObject();
            System.out.println("Leitura finalizada com sucesso");
            objLeitura.close();
            arquivoLeitura.close();
            return pok;
            
        }catch(Exception e) {
 
            System.out.println("Erro ao ler arquivo");
            return null;
        }
    }
    /**
     * Creates new form TelaConsultaGinasio
     */
    public TelaConsultaGinasio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButConsultaGin = new javax.swing.JButton();
        jButCancelConsGin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dadoGin = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Consulta Ginásio");
        setName("TelaConsultaGinasio"); // NOI18N

        jLabel2.setText("Lista de Ginasios disponíveis:");

        jButConsultaGin.setText("Consultar");
        jButConsultaGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButConsultaGinActionPerformed(evt);
            }
        });

        jButCancelConsGin.setText("Cancelar");
        jButCancelConsGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelConsGinActionPerformed(evt);
            }
        });

        dadoGin.setColumns(20);
        dadoGin.setRows(5);
        jScrollPane1.setViewportView(dadoGin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButConsultaGin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButCancelConsGin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 88, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButConsultaGin)
                    .addComponent(jButCancelConsGin))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelConsGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelConsGinActionPerformed
        // TODO add your handling code here:
        dadoGin.setText(" ");
        dispose();
    }//GEN-LAST:event_jButCancelConsGinActionPerformed
    /**
     * Lista os ginasios salvos em pokedex
     * @param evt 
     */
    private void jButConsultaGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConsultaGinActionPerformed
        Pokedex pok = Menu.getPoke();
        Ginasio infoGin;
        String str = "";
        if(pok.getNumGinasio() == 0){
            JOptionPane.showMessageDialog(null, "Não há ginasios cadastrados");
        }else{
            for(int aux = 0 ; aux < pok.getNumGinasio(); aux++){
            infoGin = pok.getObjetoGinasio(aux);
            str += "|Nome Ginasio: "+infoGin.getNomeGinasio()+"\n"+
                    "|Nome mestre ginasio: "+infoGin.getMestreGinasio()+"\n"+/*
                    "|Pokemom: "+infoGin.getPokemons()+*/"\n-----\n";
                    
        }
        dadoGin.setText(str);
        pok.getObjetoGinasioLista();
        }
        
    }//GEN-LAST:event_jButConsultaGinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dadoGin;
    private javax.swing.JButton jButCancelConsGin;
    private javax.swing.JButton jButConsultaGin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
