/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacepok;

import java.io.FileInputStream;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;
import pokemons.Informacoes;
import pokemons.Pokedex;

/**
 *
 * @author Juarez
 */
public class TelaConsultaPoke extends javax.swing.JInternalFrame {
    
    /**
     * Retorna o Objeto Pokedex Salvo
     * @return 
     */
    public Pokedex getObjecto(){
        
        try{
            
            //Carrega o arquivo
 
            FileInputStream arquivoLeitura = new FileInputStream("gravObj.dat");
            ObjectInputStream objLeitura = new ObjectInputStream(arquivoLeitura);
            Pokedex pok = (Pokedex)objLeitura.readObject();
            System.out.println("Leitura finalizada com sucesso");
            objLeitura.close();
            arquivoLeitura.close();
            return pok;
            
        }catch(Exception e) {
 
            System.out.println("Erro ao ler arquivo");
            return null;
        }
    }
    /**
     * Creates new form TelaConsultaPoke
     */
    public TelaConsultaPoke() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButConsulPoke = new javax.swing.JButton();
        jButCancelConsPoke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dadosPok = new javax.swing.JTextArea();

        setClosable(true);
        setTitle("Consulta Pokémons");
        setName("TelaConsultaPoke"); // NOI18N

        jLabel2.setText("Listagem dos Pokemons Cadastrados:");

        jButConsulPoke.setText("Consultar");
        jButConsulPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButConsulPokeActionPerformed(evt);
            }
        });

        jButCancelConsPoke.setText("Cancelar");
        jButCancelConsPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelConsPokeActionPerformed(evt);
            }
        });

        dadosPok.setColumns(20);
        dadosPok.setRows(5);
        jScrollPane1.setViewportView(dadosPok);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButConsulPoke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                        .addComponent(jButCancelConsPoke))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButConsulPoke)
                    .addComponent(jButCancelConsPoke))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelConsPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelConsPokeActionPerformed
        // TODO add your handling code here:
        dadosPok.setText(" ");
        dispose();
    }//GEN-LAST:event_jButCancelConsPokeActionPerformed
    /**
     * Retorna a lista de pokemons da pokedex que está salvo no disco
     * @return 
     */
    private void jButConsulPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButConsulPokeActionPerformed
        // TODO add your handling code here:
        Pokedex pok = Menu.getPoke();
        Informacoes infoPok;
        String str = "";
        if(pok.getNumPokemon() == 0){
            JOptionPane.showMessageDialog(null, "Não há pokemons registrados");
        }else{
            for(int aux = 0 ; aux < pok.getNumPokemon() ; aux++){
            infoPok = pok.getObjetoPokemon(aux);
            str += "|Tipo: "+/*infoPok.getTipo()+*/"\n"+
                   "|Nome: "+infoPok.getNome()+"\n"+
                   "|Sexo: "+infoPok.getSexo()+"\n"+
                    "|Habilidade: "+infoPok.getHabilidade()+"\n"+
                    "|Fraqueza: "/*+infoPok.getFraqueza()*/+"\n"+
                    "|Vantagem: "/*+infoPok.getVantagem()*/+"\n"+
                    "|Descrição: "+infoPok.getDescricao()+"\n"+
                    "|Altura: "+infoPok.getAltura()+"\n"+
                    "|Peso: "+infoPok.getPeso()+"\n"+
                    "|Seu id: "+aux+"\n"+
                    "|Id do seu pai: "+infoPok.getNumIdEvolucao()+"\n-----\n";
        }
        dadosPok.setText(str);
        pok.getObjetoPokemonLista();
        }
        
       
    }//GEN-LAST:event_jButConsulPokeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea dadosPok;
    private javax.swing.JButton jButCancelConsPoke;
    private javax.swing.JButton jButConsulPoke;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
