/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacepok;


import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import pokemons.Fogo;
import pokemons.Agua;
import pokemons.Terra;
import pokemons.Voador;
import pokemons.Normal;
import pokemons.Pokedex;
import javax.swing.JOptionPane;

/**
 *
 * @author Juarez
 */
public class TelaCadastroPokemon extends javax.swing.JInternalFrame {

     public void salvarObjeto(Pokedex obj){
        try{
            FileOutputStream arquivoGrav = new FileOutputStream("gravObj.dat");
            ObjectOutputStream objGravar = new ObjectOutputStream(arquivoGrav);
            objGravar.writeObject(obj);
            objGravar.flush();
            objGravar.close();
            System.out.println("Arquivo salvo");
            System.out.println("Objeto gravado com sucesso!");
        }catch(Exception e) {
            System.out.println("Erro ao salvar arquivo");
        }
    }
    
     public void setNumIdEvolucao(int numIdEvolucao) {
        //Instancia Pokedex para verificar se o id passado está dentro da faixa
        //existente de pokemons registrados na pokedex.
        Pokedex pokAux = new Pokedex();
        pokAux = Menu.Poke();
        if(numIdEvolucao > pokAux.getNumPokemon() || numIdEvolucao < 0){
                System.out.println("Id não válido!");
            }else{
                System.out.println("Numero de pokemons: "+pokAux.getNumPokemon());
                //analisar se vale a pena pedir para o usuário digitar o id de novo
                //e passar esse novo id como referencia a essa função ou se realmente
                //encerra sem pedir para corrigir
            }
    }
     Pokedex Aux = new Pokedex();
     
    
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastroPokemon() {
        initComponents();
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jBoxTipoPoke = new javax.swing.JComboBox<>();
        jTextNomePoke = new javax.swing.JTextField();
        jTextSexoPoke = new javax.swing.JTextField();
        jTextHabilPoke = new javax.swing.JTextField();
        jBoxFraqPoke = new javax.swing.JComboBox<>();
        jBoxVantaPoke = new javax.swing.JComboBox<>();
        jTextDescPoke = new javax.swing.JTextField();
        jTextAlturaPoke = new javax.swing.JTextField();
        jTextPesoPoke = new javax.swing.JTextField();
        jButSalvarPoke = new javax.swing.JButton();
        jButCancelPoke = new javax.swing.JButton();
        jTextEvolucao = new javax.swing.JTextField();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro Pokémon");
        setToolTipText("");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("JInterFrameCadastroPokemon"); // NOI18N

        jLabel1.setText("Tipo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Habilidade:");

        jLabel4.setText("Sexo:");

        jLabel5.setText("Evolução:");

        jLabel6.setText("Peso:");

        jLabel7.setText("Altura:");

        jLabel8.setText("Fraqueza:");

        jLabel9.setText("Descrição:");

        jLabel10.setText("Vantagem:");

        jBoxTipoPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Agua", "Fogo", "Normal", "Terra", "Voador" }));

        jBoxFraqPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Agua", "Fogo", "Normal", "Terra", "Voador" }));

        jBoxVantaPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Agua", "Fogo", "Normal", "Terra", "Voador" }));

        jButSalvarPoke.setText("Salvar");
        jButSalvarPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalvarPokeActionPerformed(evt);
            }
        });

        jButCancelPoke.setText("Cancelar");
        jButCancelPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelPokeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButSalvarPoke)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jBoxTipoPoke, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBoxFraqPoke, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextHabilPoke, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextSexoPoke)
                                    .addComponent(jTextNomePoke))))))
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBoxVantaPoke, 0, 166, Short.MAX_VALUE)
                            .addComponent(jTextDescPoke)
                            .addComponent(jTextAlturaPoke)
                            .addComponent(jTextPesoPoke)
                            .addComponent(jTextEvolucao)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButCancelPoke)
                        .addGap(125, 125, 125)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9)
                            .addComponent(jTextDescPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jTextAlturaPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jTextHabilPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPesoPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5)
                            .addComponent(jBoxFraqPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextEvolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jBoxVantaPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBoxTipoPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jTextNomePoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextSexoPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButSalvarPoke)
                    .addComponent(jButCancelPoke))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButCancelPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelPokeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButCancelPokeActionPerformed

    private void jButSalvarPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalvarPokeActionPerformed
        if(null == jBoxTipoPoke.toString()){
            JOptionPane.showMessageDialog(jPanel1, "Erro");
            
        }
        else //caso esse objeto for do tipo fogo pega as informações de cada campo e salva esse objeto
         switch (jBoxTipoPoke.toString()) {
             case "Fogo":
                 Fogo fg = new Fogo();
                 //Setando o pokemon
                 fg.setNome(jTextNomePoke.getText());
                 fg.setSexo(jTextSexoPoke.getText());
                 fg.setHabilidade(jTextHabilPoke.getText());
                 fg.setFraqueza(jBoxFraqPoke.toString());
                 fg.setVantagem(jBoxVantaPoke.toString());
                 fg.setDescricao(jTextDescPoke.getText());
                 fg.setAltura(Integer.parseInt(jTextAlturaPoke.getText()));
                 fg.setPeso(Integer.parseInt(jTextPesoPoke.getText()));
                 fg.setNumIdEvolucao(Integer.parseInt(jTextEvolucao.getText()));
                 //pega ele como do tipo fogo e salva na pokedex instanciada no Menu
                   Menu.Poke().setObjetoPokemon(fg);
                 break;
             case "Agua":
                 Agua ag = new Agua();
                 //Setando o pokemon
                 ag.setNome(jTextNomePoke.getText());
                 ag.setSexo(jTextSexoPoke.getText());
                 ag.setHabilidade(jTextHabilPoke.getText());
                 ag.setFraqueza(jBoxFraqPoke.toString());
                 ag.setVantagem(jBoxVantaPoke.toString());
                 ag.setDescricao(jTextDescPoke.getText());
                 ag.setAltura(Integer.parseInt(jTextAlturaPoke.getText()));
                 ag.setPeso(Integer.parseInt(jTextPesoPoke.getText()));
                 ag.setNumIdEvolucao(Integer.parseInt(jTextEvolucao.getText()));
                 //pega ele como do tipo fogo e salva na pokedex instanciada no Menu
                 Menu.Poke().setObjetoPokemon(ag);
                 break;
             case "Normal":
                 Normal nm = new Normal();
                 //Setando o pokemon
                 nm.setNome(jTextNomePoke.getText());
                 nm.setSexo(jTextSexoPoke.getText());
                 nm.setHabilidade(jTextHabilPoke.getText());
                 nm.setFraqueza(jBoxFraqPoke.toString());
                 nm.setVantagem(jBoxVantaPoke.toString());
                 nm.setDescricao(jTextDescPoke.getText());
                 nm.setAltura(Integer.parseInt(jTextAlturaPoke.getText()));
                 nm.setPeso(Integer.parseInt(jTextPesoPoke.getText()));
                 nm.setNumIdEvolucao(Integer.parseInt(jTextEvolucao.getText()));
                 //pega ele como do tipo fogo e salva na pokedex instanciada no Menu
                 Menu.Poke().setObjetoPokemon(nm);
                 break;
             case "Terra":
                 Terra tr = new Terra();
                 //Setando o pokemon
                 tr.setNome(jTextNomePoke.getText());
                 tr.setSexo(jTextSexoPoke.getText());
                 tr.setHabilidade(jTextHabilPoke.getText());
                 tr.setFraqueza(jBoxFraqPoke.toString());
                 tr.setVantagem(jBoxVantaPoke.toString());
                 tr.setDescricao(jTextDescPoke.getText());
                 tr.setAltura(Integer.parseInt(jTextAlturaPoke.getText()));
                 tr.setPeso(Integer.parseInt(jTextPesoPoke.getText()));
                 tr.setNumIdEvolucao(Integer.parseInt(jTextEvolucao.getText()));
                 //pega ele como do tipo fogo e salva na pokedex instanciada no Menu
                 Menu.Poke().setObjetoPokemon(tr);
                 break;
             case "Voador":
                 Voador vd = new Voador();
                 //Setando o pokemon
                 vd.setNome(jTextNomePoke.getText());
                 vd.setSexo(jTextSexoPoke.getText());
                 vd.setHabilidade(jTextHabilPoke.getText());
                 vd.setFraqueza(jBoxFraqPoke.toString());
                 vd.setVantagem(jBoxVantaPoke.toString());
                 vd.setDescricao(jTextDescPoke.getText());
                 vd.setAltura(Integer.parseInt(jTextAlturaPoke.getText()));
                 vd.setPeso(Integer.parseInt(jTextPesoPoke.getText()));
                 vd.setNumIdEvolucao(Integer.parseInt(jTextEvolucao.getText()));
                 //pega ele como do tipo fogo e salva na pokedex instanciada no Menu
                 Menu.Poke().setObjetoPokemon(vd);
                 break;
             default:
                // JOptionPane.showMessageDialog(jPanel1, "Erro");
                 break;
         }
      Menu.Poke().getObjetoPokemonLista();
      salvarObjeto(Menu.Poke()); //salva o objeto
      //Menu.Poke().getObjetoPokemonLista();
      //confere se tem algo na nossa pokedex e então limpa os campos
      if(Menu.Poke() != null){
      jTextAlturaPoke.setText("");
      jTextDescPoke.setText("");
      jTextEvolucao.setText("");
      jTextHabilPoke.setText("");
      jTextNomePoke.setText("");
      jTextPesoPoke.setText("");
      jTextSexoPoke.setText("");
      jBoxFraqPoke.setSelectedIndex(0);
      jBoxTipoPoke.setSelectedIndex(0);
      jBoxVantaPoke.setSelectedIndex(0);
      }
      else{
      JOptionPane.showMessageDialog(jPanel1, "Erro");
      }
      
      
    }//GEN-LAST:event_jButSalvarPokeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> jBoxFraqPoke;
    public javax.swing.JComboBox<String> jBoxTipoPoke;
    public javax.swing.JComboBox<String> jBoxVantaPoke;
    public javax.swing.JButton jButCancelPoke;
    public javax.swing.JButton jButSalvarPoke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextAlturaPoke;
    public javax.swing.JTextField jTextDescPoke;
    public javax.swing.JTextField jTextEvolucao;
    public javax.swing.JTextField jTextHabilPoke;
    public javax.swing.JTextField jTextNomePoke;
    public javax.swing.JTextField jTextPesoPoke;
    public javax.swing.JTextField jTextSexoPoke;
    // End of variables declaration//GEN-END:variables
}
