/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacepok;

import pokemons.Ginasio;

/**
 *
 * @author Juarez
 */
public class TelaCadastroGinasio extends javax.swing.JInternalFrame {
    Ginasio gin;
    /**
     * Creates new form TelaCadastroGinasio
     */
    public TelaCadastroGinasio() {
        initComponents();
        this.gin = new Ginasio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextNomeGin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextMestreGin = new javax.swing.JTextField();
        jBoxCadPoke = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButSalvaGin = new javax.swing.JButton();
        jButCancelGin = new javax.swing.JButton();
        jLabelIdPoke = new javax.swing.JLabel();
        jTextIdPoke = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro Ginásios");
        setName("TelaCadGinasio"); // NOI18N

        jLabel1.setText("Nome ginásio:");

        jTextNomeGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeGinActionPerformed(evt);
            }
        });

        jLabel2.setText("Mestre ginásio:");

        jTextMestreGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMestreGinActionPerformed(evt);
            }
        });

        jBoxCadPoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jBoxCadPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxCadPokeActionPerformed(evt);
            }
        });

        jLabel3.setText("Cadastro de pokemon:");

        jButSalvaGin.setText("Salvar");
        jButSalvaGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButSalvaGinActionPerformed(evt);
            }
        });

        jButCancelGin.setText("Cancelar");
        jButCancelGin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCancelGinActionPerformed(evt);
            }
        });

        jLabelIdPoke.setText("Digite o Id:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addComponent(jButSalvaGin))
                    .addComponent(jLabelIdPoke))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNomeGin)
                            .addComponent(jTextMestreGin)
                            .addComponent(jBoxCadPoke, 0, 180, Short.MAX_VALUE))
                        .addComponent(jButCancelGin))
                    .addComponent(jTextIdPoke))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextNomeGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextMestreGin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoxCadPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdPoke)
                    .addComponent(jTextIdPoke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButSalvaGin)
                    .addComponent(jButCancelGin))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNomeGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeGinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNomeGinActionPerformed

    private void jTextMestreGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMestreGinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMestreGinActionPerformed

    private void jButCancelGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCancelGinActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButCancelGinActionPerformed

    private void jBoxCadPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxCadPokeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBoxCadPokeActionPerformed

    private void jButSalvaGinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButSalvaGinActionPerformed
        // TODO add your handling code here:
                 
                    gin.setNomeGinasio(jTextNomeGin.getText());
                    gin.setMestreGinasio(jTextMestreGin.getText());
                    if("Sim".equals(jBoxCadPoke.toString())){
                    gin.setPokemons((Menu.Poke().getObjetoPokemon(Integer.parseInt(jTextIdPoke.getText()))));
                    }
                    Menu.Poke().setObjetoGinasio(gin);
                  
                    if(Menu.Poke() != null){
                    jTextIdPoke.setText("");
                    jTextMestreGin.setText("");
                    jTextNomeGin.setText("");
                     
                    }
                    
    }//GEN-LAST:event_jButSalvaGinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxCadPoke;
    private javax.swing.JButton jButCancelGin;
    private javax.swing.JButton jButSalvaGin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelIdPoke;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextIdPoke;
    private javax.swing.JTextField jTextMestreGin;
    private javax.swing.JTextField jTextNomeGin;
    // End of variables declaration//GEN-END:variables
}
